### ISSUE TITLE
Verkeerde soortnaam bij aantal soorten

### ISSUE THREAD

**Issue by Desharin** [Desharin/VERA-issues#10]
Bij een aantal soorten (synoniemen?) verandert de soortnaam na de invoer. De soort komt wel correct in de Verspreidingsatlas.
Voorbeelden:
Draba verna -> Erophila verna.
Ficaria verna -> Ranunculus ficaria subsp. bulbilifer.
Elymus repens -> Elymus repens subsp. repens.
Euonymus fortunei -> Euonymus hederaceus.

**Comment by laurenssparrius** [comment]
Niet aanpassen, maar misschien wel in de keuzelijst aangeven als een synoniem wordt getoond.
