### ISSUE TITLE
Lange keuzelijsten habitat, substraat, organisme anders indelen

### ISSUE THREAD

**Issue by laurenssparrius** [Desharin/VERA-issues#17]
De keuzelijst voor bijv. habitat is erg lang. Kijken of we dit anders kunnen weergeven, bijv. door de filteren op hoofdcategorie of beginletter.

**Comment by jlangens** [comment]
Beste mensen, de lijsten voor habitat, substraat en organisme zijn niet werkbaar. De lijsten zijn lang, niet eens op alfabetische volgorde en zonder mogelijkheid de lijst te verkorten door letters in te typen die in de naam terugkomen. Ik daag jullie uit 4 paddenstoelen in te voeren mèt habitat, substraat en organisme. Dat betekent scrollen, scrollen en nog eens scrollen. NMV wil deze gegevens graag zien bij de waarneming,  maar op deze manier is dat ondoenlijk. Jammer ook dat  bij het ontwikkelen van de Vera-app geen verbetering is meegenomen, want in Nova was dat ook al zo. Dit is echt geen lange termijn-wens.
