### ISSUE TITLE
Kom niet voorbij laadscherm zonder internet

### ISSUE THREAD

**Issue by Desharin** [Desharin/VERA-issues#25]
Een aantal mensen geven aan geen mobiel internet te hebben, en dan in het veld de melding te krijgen dat de soortgroepen moeten worden geüpdate. Gezien zij geen internet hebben kunnen ze niet voorbij dit scherm komen.

Er zijn twee mogelijkheden waardoor dit veroorzaakt kan worden:
1. De app is nog niet eerder met internet geopend, hierdoor zijn er geen soortenlijsten aanwezig.
2. De app is begonnen met soortenlijsten updaten terwijl er wel internet was, maar het internet viel tijdens het update proces weg.

Dit is een lastig probleem: De soortenlijsten moeten juist worden ingeladen, anders kan de app crashen bij het laden van de waarnemingen. Daarom is het op dit moment niet mogelijk voorbij het laadscherm te komen zonder dat de soortenlijsten zijn ingeladen.

Geval 1. is een probleem. In principe gaat het hier om een gebruikersfout, maar wel een logische. We zouden duidelijker kunnen aangeven dat de app eerst met een internetverbinding moet worden opgestart om de soortenlijsten op te halen.
Anderzijds zouden we een soortenlijst kunnen bijleveren. Hierbij is het probleem dat de bijgeleverde soortenlijst up-to-date moet zijn, want als de gebruiker een waarneming heeft ingevuld van een soort die niet voorkomt op de oude soortenlijst, kan de app crashen wanneer deze waarneming wordt bekeken.

Geval 2. is een edge-case, hier hoeft in principe geen oplossing voor te komen. In theorie zou voor het updaten van de soortenlijsten een back-up hiervan kunnen worden gemaakt. Mocht het updaten fout gaan kan deze back-up terug worden gezet.

Graag meningen over hoe dit het best op te lossen is.

**Comment by Desharin** [comment]
Mijn voorstel is het volgende:

Voor geval 1. zetten we een disclaimer in de app store dat de app eerst een keer met internet moet worden geopend.
Verder voegen we een melding toe aan het laadscherm als je de app voor het eerst opstart dat een internet verbinding vereist is.

Voor geval 2. maken we een back-up van de soortenlijsten bij het updaten, zodat we deze terug kunnen plaatsen als het updaten mislukt.

**Comment by Desharin** [comment]
Er is mogelijk een probleem met de database van de app bij het upgraden van een beta-versie naar 1.0.0.
Dit wordt momenteel onderzocht.

**Comment by Desharin** [comment]
dart-lang/http#627

Er lijkt een probleem te zijn met met de SSL op devices met android 6 t/m android 7.0 (android 7.1 en hoger werkt wel).
Deze devices vertrouwen geen self-signed certificates, maar kennen ook geen LetsEncrypt. Hierdoor ondersteunen deze nu geen https API calls naar de Verspreidingsatlas.

**Comment by JaapGd** [comment]
Ik heb Vera in gebruik op mijn tablet en al lijsten gemaakt. Nu start Vera op met de melding dat de soortenlijst nu niet kan worden opgehaald. Moet verbinden met internet.

**Comment by Desharin** [comment]
Versie 1.0.1 zou deze bug moeten oplossen, graag hoor ik het als dit probleem zich nog steeds voordoet bij de nieuwe versie.
