### ISSUE TITLE
Uploadresultaten in mail

### ISSUE THREAD

**Issue by HermanEH** [Desharin/VERA-issues#27]
Komt er een optie om na uploaden de resultaten in de mail te ontvangen?

**Comment by Desharin** [comment]
@laurenssparrius Willen we dit in Vera hebben? 
Wat staat er op dit moment in die e-mail? Als we een mail willen versturen moet dat vanuit de Verspreidingsatlas gebeuren.
Als alternatief kunnen we ook een notificatie naar de app sturen.
Zie [Firebase](https://firebase.google.com/docs/cloud-messaging/).

**Comment by HermanEH** [comment]
Waar het makkelijk voor is:
- bevestiging dat de upload is geslaagd
- in een werkgroep is het delen van de inventarisatie makkelijker dan een link naar de streeplijst. Niet iedereen heeft een account en er zijn mensen die niet vaardig zijn met de PC
- bij nadeterminatie door andere leden kunnen de verbeteringen makkelijker doorgevoerd worden en toegevoegd aan de streeplijst

**Comment by laurenssparrius** [comment]
Interessant om te verkennen of we push-berichten in de app kunnen tonen.
Maar het is meer iets voor het najaar.
Ik heb hier uitleg gevonden
https://stackoverflow.com/questions/38184432/fcm-firebase-cloud-messaging-push-notification-with-asp-net
Er moet dan voor ieder apparaat waarop de app staat een token (device id)
zijn. Daarnaast moet er een ApiKey voor inloggen op FireBase en SenderId
komen (Verspreidingsatlas).

Groet, Laurens

Op wo 30 mrt. 2022 om 14:24 schreef Dion van der Hak <
***@***.***>:
