### ISSUE TITLE
In app gewiste foto's worden meegestuurd naar Verspreidingsatlas

### ISSUE THREAD

**Issue by laurenssparrius** [Desharin/VERA-issues#42]
Situatie: gebruiker voegt een foto toe aan een waarneming en verwijdert deze weer
Probleem: bij het uploaden worden ook de verwijderde foto's geupload. In de Verspreidingsatlas worden deze niet verder verwerkt en moeten handmatig worden verwijderd.
Oplossing: verwijderde foto's niet uploaden.

**Comment by Desharin** [comment]
Ik kan dit niet reproduceren. Als ik een foto maak bij een waarneming, deze verwijder, en dan de waarneming upload zie ik de foto niet terug bij de waarneming op Verspreidingsatlas.

**Comment by laurenssparrius** [comment]
Dit probleem is na 14 juni niet meer voorgekomen, daarom afgemeld
