### ISSUE TITLE
Lijst kan niet verstuurd worden als fotobestanden ontbreken

### ISSUE THREAD

**Issue by Desharin** [Desharin/VERA-issues#44]
Mocht een fotobestand verwijderd zijn of corrupt zijn geraakt, kan de hele lijst waar de waarneming met deze foto inzit niet meer verstuurd worden. In theorie zou dit niet voor moeten kunnen komen, maar er is nu 1 report waar het wel gebeurd.

Oplossing: Check bij het versturen of de foto bestaat, zo niet, verwijder deze dan uit de lijst met foto's bij de waarneming en ga door met versturen.

**Comment by laurenssparrius** [comment]
mogelijk dezelfde als #42 waarbij foto's geupload worden, maar niet de waarnemingen zelf
