### ISSUE TITLE
Sla huidige status app op & implementeer juiste life-cycle functies

### ISSUE THREAD

**Issue by Desharin** [Desharin/VERA-issues#45]
Goede apps bewaren vaak de huidige pagina, de navigator route ernaartoe en de status van formulieren.
Deze opgeslagen gegevens worden gebruikt voor als de app onverwachts gesloten wordt, bijvoorbeeld door het geheugen beheer van de telefoon.
De volgende punten moeten worden geïmplementeerd:
- Sla de huidige navigator route en pagina op, inclusief eventuele UUIDs van formulieren of waarnemingen.
- Sla de ingevulde waarden van invoervelden op.
- Na onverwacht sluiten, navigeer naar de juiste pagina, herconstrueer de navigator route en vul eventueel velden in.
- Implementeer de functie met de foto library waarmee deze de foto alsnog naar de app pusht nadat we de pagina hebben geherconstrueerd.

Zie https://api.flutter.dev/flutter/services/RestorationManager-class.html en https://api.flutter.dev/flutter/widgets/RestorationMixin-mixin.html

**Comment by laurenssparrius** [comment]
We zien momenteel 0 of 1 crashes per maand in de statistieken op 500 gebruikers, dus het is maar de vraag of dit nodig is.

**Comment by Desharin** [comment]
Het gaat hier niet om crashes. Maar op telefoons met weinig RAM (of agressief geheugenbeheer) kan een telefoon een app sluiten als deze in de achtergrond staat. Dus bij gebruik van de camera, als je gebeld wordt, of als een gebruiker op een notificatie van een andere app tikt. Dan moet de app op dit moment weer helemaal opnieuw opstarten in plaats van dat ie doorgaat waar ie gebleven is.
