### ISSUE TITLE
Looproutes met multipolygon worden niet getoond

### ISSUE THREAD

**Issue by laurenssparrius** [Desharin/VERA-issues#46]
Looproutes met een multipolygon worden niet op de kaart getoond en gebruikt voor controle van de gebruikerslocatie.

**Comment by Desharin** [comment]
Dat klopt, er is op dit moment geen ondersteuning voor multipolygonen. Ik kan deze wel toevoegen als dat nodig is. Voor welk project worden multipolygonen gebruikt?

**Comment by laurenssparrius** [comment]
Bij LMF-A is er nu een route met een multipolygon en dat worden er misschien meer. Oplossing voor nu is om de delen te verbinden.
