### ISSUE TITLE
Foto's van telgebieden

### ISSUE THREAD

**Issue by laurenssparrius** [Desharin/VERA-issues#47]
Voor Nectarindex en andere tellingen met vaste meetpunten willen we situatiefoto's gaan vastleggen. Bijvoorbeeld een overzichtsfoto van een berm. In de app moet een fotogallerij komen, net als bij de waarnemingen. Het bericht aan de server bevat de nieuwe sleutel form.pictures (op dezelfde manier als observation.pictures). De achterkant van het systeem is al voorbereid op het verwerken van deze formulierfoto's.

**Comment by Desharin** [comment]
Aan welke protocollen wil je deze functie toegevoegd hebben? Of allemaal?
