### ISSUE TITLE
Optie 'Soort onbekend' kunnen invoeren

### ISSUE THREAD

**Issue by NormanGraafsma** [Desharin/VERA-issues#57]
Het komt voor dat je niet weer welke soort je voor je neus hebt, maar niet weer welk soort, niet eens het geslacht, het zou dan prettig zijn als je kunt kiezen voor soort onbekend. 

Per soortgroep zou afdoende zijn. Bijv. 

Mos onbekend - Bryophyte species. 

Als. workaround kies ik de bovenste soort en pas ik die later aan als ik de soort weet, of verwijder deze als deze niet op naam brengen kan.

**Comment by Desharin** [comment]
Op dit moment zijn Plantae sp. (plant (soort onbekend)), Bryophyta sp. (mos (soort onbekend)) en Lichenes sp. (korstmos (soort onbekend)) al opties bij het invoeren. Het is mij niet helemaal duidelijk wat je verdere wensen hiervoor zijn.

**Comment by NormanGraafsma** [comment]
Bedankt voor het wakker maken. Dit was een pebcak foutje mijnerzijds. 
Dit verzoek kan verwijderd worden.

**Comment by Desharin** [comment]
Top!
