### ISSUE TITLE
"<Soort> onbekend" zou automatisch naar 'Determinatie onzeker' moeten gaan.

### ISSUE THREAD

**Issue by NormanGraafsma** [Desharin/VERA-issues#58]
Als je nu een soort invoert die nog niet op naam is gebracht, dan wordt de standaard instelling overgenomen en kan het zijn dat deze als 'Determinatie zeker' geüpload wordt. Dat wordt vast aan de achterkant ondervangen, maar als een "<Soort>  onbekend" ingevoerd wordt en hij staat op zeker, dan is de kans kleiner dat deze door de waarnemer alsnog gedetermineerd wordt. 

Bijv. Acremonium [soort onbekend]. Deze komt als zekere waarneming in de lijst als jezelf niks aanpast.

**Comment by Desharin** [comment]
@laurenssparrius Ik vind dit een lastige. De waarnemer is natuurlijk wel zeker dat het om een Acremonium gaat, maar weet (nu) niet welke. Technisch gezien is de waarneming dus zeker, alleen zou deze preciezer kunnen. Graag jouw mening hierover.

**Comment by NormanGraafsma** [comment]
@Desharin kleine toevoeging ter verduidelijking.

Ik misbruik nu _Acremonium [soort onbekend]_ omdat ik niet kan kiezen voor bijv. _Mos onbekend_ (zie ook [dit](https://github.com/Desharin/VERA-issues/issues/57) verbetervoorstel) en pak de eerste de beste soort die gemarkeerd staat als _Onbekend_. 

Maar ik ben er in dit geval zeker van de _Acremonium_ niet klopt en in mijn geval voorlopig ook niet zal kloppen, omdat ik naar mossen kijk en niet naar korstmossen.

**Comment by laurenssparrius** [comment]
Liever op een andere manier aangeven dat het om een onzekere waarneming gaat. Beter is een soortnaam invoeren waarvan je denkt dat die het is, en dan "onzeker" aanvinken. Dan hoeven er geen twee dingen aangepast te worden in het validatieproces.

**Comment by NormanGraafsma** [comment]
Hi Laurens, 

Zie mijn andere verbetervoorstel, dat dit 'probleem' zou oplossen. Ik zou nu niet weten hoe dit anders op te lossen. 
Soms weet ik in het veld niet om welk geslacht het gaat, maar wil ik wel de vindplaats vastleggen. 

Ik probeer nu handmatig deze op onzeker te zetten en ga thuis verder sleutelen, maar het is een risico dat ik onbedoeld een keer vergeet de waarneming op onzeker te zetten en daarmee extra werk creëer voor de validatoren. 

Als het andere verbetervoorstel opgelost wordt, dan vervalt het belang van dit voorstel zo goed als.

**Comment by NormanGraafsma** [comment]
@laurenssparrius & @Desharin ook dit verzoek mag gesloten worden, daar het 'probleem' is opgelost met de oplossing van @Desharin in [DIT](https://github.com/Desharin/VERA-issues/issues/57) verbetervoorstel.
