### ISSUE TITLE
Wisselen tussen wetenschappelijke en Nederlandse naam

### ISSUE THREAD

**Issue by Desharin** [Desharin/VERA-issues#7]
Niet voor alle floristen is het handig als de wetenschappelijke naam de hoofdnaam is. Bijvoorbeeld bij sorteren of de kieslijst zou ook de Nederlandse naam de hoofdnaam mogen zijn. Hiervoor kan een optie in het instellingen menu.

**Comment by laurenssparrius** [comment]
Inderdaad in het instellingenmenu één keuze voor NL / Wet namen maken. In de andere weergaven wet/nl dan omwisselen en sorteervolgorde aanpassen.
