### ISSUE TITLE
Sorteervolgorde autocomplete lijst invoervak soortnaam

### ISSUE THREAD

**Issue by laurenssparrius** [Desharin/VERA-issues#82]
Invoer van 'des' levert eerst een alfabetische lijst op met soort zonder Nederlandse  naam. Daarna een alfabetische lijst met soorten met een Nederlandse naam.

Gewenste verbetering: sorteer op wetnaam als de primaire 'taal' wetenschappelijk is. Sorteer op NL-naam als de primaire taal NL is. Is het laatste geval komen soorten zonder NL-naam onderaan te staan.

**Comment by Desharin** [comment]
Graag meer uitleg bij deze issue. Op dit moment lijkt de sortering te doen wat er gevraagd wordt:
Als de taal op Nederlands staat en je "des" intypt, komen als eerste de soorten waarvan de Nederlandse naam begint met "Des".
Echter omdat een aantal soorten dezelfde Nederlandse en Wetenschappelijke naam hebben (zoals Deschampsia antarctica) komen deze naar boven.
Ik zou een check kunnen inbouwen dat wanneer de Nederlandse en Wetenschappelijke naam hetzelfde zijn, de Nederlandse naam genegeerd wordt. Dan zou Descurainia (G) [soort onbekend) bovenaan komen, gevolgd door Dessertbladen.

**Comment by laurenssparrius** [comment]
Mijn voorkeur heeft dan:

Alleen als de waarnemer de NL-naam als voorkeurstaal heeft ingesteld, sorteer de keuzelijst dan op:

1. Exacte match NL of WET
2. NL-naam is niet leeg en niet gelijk aan WET
3. Alfabetisch

Stap 2 is nieuw.
